#!/usr/bin/env python

import sys

from rqt_user_interface.rqt_user_interface import RqtFlexGrasp
from rqt_gui.main import Main

plugin = 'rqt_user_interface' #
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
