#!/usr/bin/env python

import sys

from rqt_user_interface.rqt_user_interface import RqtImageProcessing
from rqt_gui.main import Main

plugin = 'rqt_image_processing' #
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
