#!/usr/bin/env python

import sys

from rqt_sdh_grasp.rqt_sdh_grasp import RqtSdhGrasp
from rqt_gui.main import Main

plugin = 'rqt_sdh_grasp'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
